service: serverless-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-west-2

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
  
  getLoot:
    handler: src/handler.getLoot
    events:
      - http:
          path: get_loot
          method: get