service: serverless-api

provider:
  name: aws
  runtime: nodejs24.x
  stage: dev
  region: eu-west-2
  frameworkVersion: '~4.40.0'

functions:
  hello:
    handler: dist/handler.hello
    events:
      - http:
          path: hello
          method: get

  getLoot:
    handler: dist/handler.getLoot
    events:
      - http:
          path: get_loot
          method: get

  # Prothero endpoints removed (EOL)