service: serverless-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "arn:aws:dynamodb:us-east-1:*:table/protheroDB"

functions:
  hello:
    handler: dist/handler.hello
    events:
      - http:
          path: hello
          method: get

  getLoot:
    handler: dist/handler.getLoot
    events:
      - http:
          path: get_loot
          method: get